export interface ImageData {
  _id: string;
  thumb: string;
  path: string;
  user_name: string;
  user_url: string;
  photo_url: string;
}

// prettier-ignore
export const images: ImageData[] = [
  { _id: 'F4ms1MRoUMg', thumb: '/assets/images/gallery/F4ms1MRoUMg-small.jpg', path: '/assets/images/gallery/F4ms1MRoUMg.jpg', user_name: 'Karsten Winegeart', user_url: 'https://unsplash.com/@karsten116?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/F4ms1MRoUMg?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: '6kCjK2JFa2U', thumb: '/assets/images/gallery/6kCjK2JFa2U-small.jpg', path: '/assets/images/gallery/6kCjK2JFa2U.jpg', user_name: 'Marcelina Pawlikowska', user_url: 'https://unsplash.com/@pawlikowska?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/6kCjK2JFa2U?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'L1YOKkbZ5q0', thumb: '/assets/images/gallery/L1YOKkbZ5q0-small.jpg', path: '/assets/images/gallery/L1YOKkbZ5q0.jpg', user_name: 'BAILEY MAHON', user_url: 'https://unsplash.com/@baileymahon?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/L1YOKkbZ5q0?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'CFGUlqXUV-4', thumb: '/assets/images/gallery/CFGUlqXUV-4-small.jpg', path: '/assets/images/gallery/CFGUlqXUV-4.jpg', user_name: 'Dave Goudreau', user_url: 'https://unsplash.com/@davegoudreau?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/CFGUlqXUV-4?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'MOW2lUj45ZQ', thumb: '/assets/images/gallery/MOW2lUj45ZQ-small.jpg', path: '/assets/images/gallery/MOW2lUj45ZQ.jpg', user_name: 'Anne Sack', user_url: 'https://unsplash.com/@anne_sack?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/MOW2lUj45ZQ?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'AQG3danx81Y', thumb: '/assets/images/gallery/AQG3danx81Y-small.jpg', path: '/assets/images/gallery/AQG3danx81Y.jpg', user_name: 'Pursuit Retro', user_url: 'https://unsplash.com/@pursuitretro?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/AQG3danx81Y?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'SHkO_kXJWaA', thumb: '/assets/images/gallery/SHkO_kXJWaA-small.jpg', path: '/assets/images/gallery/SHkO_kXJWaA.jpg', user_name: 'Harry Shelton', user_url: 'https://unsplash.com/@itsharryshelton?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/SHkO_kXJWaA?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: '8-ci6kNyuwc', thumb: '/assets/images/gallery/8-ci6kNyuwc-small.jpg', path: '/assets/images/gallery/8-ci6kNyuwc.jpg', user_name: 'Sebastian Mittermeier', user_url: 'https://unsplash.com/@schmittermeier?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/8-ci6kNyuwc?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'V4MxXxS2WWI', thumb: '/assets/images/gallery/V4MxXxS2WWI-small.jpg', path: '/assets/images/gallery/V4MxXxS2WWI.jpg', user_name: 'Erik Mclean', user_url: 'https://unsplash.com/@introspectivedsgn?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/V4MxXxS2WWI?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'S1sdXkQaXiU', thumb: '/assets/images/gallery/S1sdXkQaXiU-small.jpg', path: '/assets/images/gallery/S1sdXkQaXiU.jpg', user_name: 'Evie S.', user_url: 'https://unsplash.com/@evieshaffer?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/S1sdXkQaXiU?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'b3pbOt-7UjQ', thumb: '/assets/images/gallery/b3pbOt-7UjQ-small.jpg', path: '/assets/images/gallery/b3pbOt-7UjQ.jpg', user_name: 'Maurits Bausenhart', user_url: 'https://unsplash.com/@maur1ts?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/b3pbOt-7UjQ?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'SFj3E3uivQo', thumb: '/assets/images/gallery/SFj3E3uivQo-small.jpg', path: '/assets/images/gallery/SFj3E3uivQo.jpg', user_name: 'Himiway Bikes', user_url: 'https://unsplash.com/@himiwaybikes?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/SFj3E3uivQo?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'TE_lOmkKq04', thumb: '/assets/images/gallery/TE_lOmkKq04-small.jpg', path: '/assets/images/gallery/TE_lOmkKq04.jpg', user_name: 'Tim Schmidbauer', user_url: 'https://unsplash.com/@timschmidbauer?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/TE_lOmkKq04?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'JMw3uw94Wc4', thumb: '/assets/images/gallery/JMw3uw94Wc4-small.jpg', path: '/assets/images/gallery/JMw3uw94Wc4.jpg', user_name: 'Nataliya Melnychuk', user_url: 'https://unsplash.com/@natinati?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/JMw3uw94Wc4?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'nRWnmOMiBh4', thumb: '/assets/images/gallery/nRWnmOMiBh4-small.jpg', path: '/assets/images/gallery/nRWnmOMiBh4.jpg', user_name: 'Chase Baker', user_url: 'https://unsplash.com/@sandbarproductions?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/nRWnmOMiBh4?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'GZNNYASHudg', thumb: '/assets/images/gallery/GZNNYASHudg-small.jpg', path: '/assets/images/gallery/GZNNYASHudg.jpg', user_name: 'Red John', user_url: 'https://unsplash.com/@redjohn45?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/GZNNYASHudg?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'izPZjLPrc8s', thumb: '/assets/images/gallery/izPZjLPrc8s-small.jpg', path: '/assets/images/gallery/izPZjLPrc8s.jpg', user_name: 'Robert Gomez', user_url: 'https://unsplash.com/@lifeofrobbie?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/izPZjLPrc8s?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: '_bO_RFCRbeA', thumb: '/assets/images/gallery/_bO_RFCRbeA-small.jpg', path: '/assets/images/gallery/_bO_RFCRbeA.jpg', user_name: 'Jon Tyson', user_url: 'https://unsplash.com/@jontyson?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/_bO_RFCRbeA?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'RwvwxBjPnsI', thumb: '/assets/images/gallery/RwvwxBjPnsI-small.jpg', path: '/assets/images/gallery/RwvwxBjPnsI.jpg', user_name: 'Maksym Tymchyk', user_url: 'https://unsplash.com/@maksym_tymchyk?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/RwvwxBjPnsI?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
  { _id: 'cPQb0_u6x88', thumb: '/assets/images/gallery/cPQb0_u6x88-small.jpg', path: '/assets/images/gallery/cPQb0_u6x88.jpg', user_name: 'Y MORAN', user_url: 'https://unsplash.com/@ymoran?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit', photo_url: 'https://unsplash.com/photos/cPQb0_u6x88?utm_source=unsample&utm_medium=referral&utm_campaign=api-credit' },
];
